import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container:{
      width: '100%', 
      height: '100%',
    },
    scrollView: {
      margin:0,
      flex: 1,
      padding: 0,
      width: '100%',
      height: '100%',
    },
    viewBanner:{
      alignContent: 'center',
      height: '10%',
      width: '100%',
      marginTop: 20,
      padding: 0,
    },
    banner:{
      width: '100%',
      height: '100%',
      padding:0,
    },
    appContainer: {
      marginHorizontal: '5%',
      marginBottom: '60%',
      height:'100%',
      marginTop: '5%',
      padding: 10,
      borderWidth: 1,
      borderColor: '#49106D',
      borderRadius: 5,
      backgroundColor: 'rgba( 93, 32, 134, 0.4 )',
      alignItems: 'center',
      
    },
    titulo:{
      backgroundColor: '#49106D',
      width: '100%',
      marginBottom: 10
    },
    texto:{
      alignContent: 'center',
      textAlign: 'center',
      fontSize: 16,
      fontWeight: 'bold',
      marginVertical: '10%',
      color: '#FFF',
      // borderBottomWidth: 1,
      // borderBottomColor: '#000',
    },
    input:{
      marginBottom: 20,
      color: '#FFF',
      borderWidth: 1,
      borderColor: '#49106D',
      //backgroundColor: 'rgba( 93, 32, 134, 0.7 )',
      backgroundColor: 'rgba(20, 213, 72, 0.4 )',
      borderRadius: 5,
      height: 60,
      width: '100%',
      fontSize: 16,
      fontWeight: 'bold',
      paddingLeft: 15,
    },
    viewCep:{
      flexDirection: 'row', 
      //margin: 0,
      height: 60,
      marginBottom: 20,
    },
    inputCep:{
      color: '#FFF',
      borderWidth: 1,
      borderColor: '#49106D',
      borderRadius: 5,
      height: '100%',
      width: '60%',
      fontSize: 16,
      fontWeight: 'bold',
      backgroundColor: 'rgba(20, 213, 72, 0.4 )',
    },
    botaoCep:{
      width: '35%',
      height: '100%',
      alignItems: 'center',
      alignContent: 'center',
      justifyContent: 'center',
      marginHorizontal: 10,
      borderRadius: 5,
      backgroundColor: '#49106D',
    },
    textoDados:{
      fontWeight: 'bold',
      color:'#FFF',
      fontSize:18,
      padding: 10,
      marginVertical: 10,
      borderWidth: 1,
      borderRadius: 5,
      backgroundColor: 'rgba(20, 213, 72, 0.4 )',
      borderColor: '#49106D',
    },
    viewDados:{
      borderWidth: 1,
      borderColor: '#49106D',
      borderRadius: 5,
      backgroundColor: 'rgba( 93, 32, 134, 0.4 )',
      alignItems: 'center'
    },
    viewBotoes:{
      flexDirection: 'row',
      height: '10%',
    },
    viewDados:{
      //borderWidth: 1,
      //borderColor: '#49106D',
      marginBottom: 25,
      borderRadius: 5,
      paddingLeft: 0,
      width: '100%',
    },
    viewPicker:{
      flexDirection: 'row', 
    //   alignItems: 'flex-start', 
      borderWidth: 1,
      borderColor: '#49106D',
      backgroundColor: 'rgba(20, 213, 72, 0.4 )',
      marginBottom: 25,
      borderRadius: 5,
      paddingLeft: 0,
      height: 60,
      paddingHorizontal: 10,
    },
    picker:{
      height: 50, 
      width: 150,
      padding: -40,
      color: '#FFF', 
      fontWeight: 'bold'
    },
    ViewPickerText:{
      padding: 15,
      fontSize: 16,
      fontWeight: 'bold',
      color: '#FFF',
    },
    botoes:{
      width: '35%',
      height: '100%',
      alignItems: 'center',
      alignContent: 'center',
      justifyContent: 'center',
      marginHorizontal: 10,
      marginVertical: 10,
      borderRadius: 5,
      backgroundColor: '#49106D',
    },
  
    textBotoes:{
      fontSize: 16,
      fontWeight: 'bold',
      color: '#FFF',
    }
  });
  
export default styles;